[package]
name = "uefi_game"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
uefi = "0.35.0"

[profile.dev]
panic = "abort" # Na bare-metal panic musi kończyć program natychmiastowo

[profile.release]
panic = "abort"
